name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
          cache: false
      - run: |
          chmod ugo+x *.sh
          export CXX="$(pwd)/zig-clang++.sh"
          export CC="$(pwd)/zig-clang-cc.sh"
          pip install -r requirements.txt
          python -m nuitka --show-scons --clang --stand-alone hello.py
          ./hello.dist/hello.bin
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: |
            nuitka-crash-report.xml
            hello.dist/**/*
          
