name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          chmod ugo+x *.sh
          mv zig-cc.sh clang-cc.sh
          export CXX="$(pwd)/zig-clang++.sh"
          export CC="$(pwd)/clang-cc.sh"
          pip install -r requirements.txt
          python -m nuitka --show-scons --lto=no hello.py
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: nuitka-crash-report.xml
          
