name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python_version:
          # - '3.9'
          - '3.10'
          # - '3.11'
        os:
          - ubuntu-latest
          - windows-latest
          # - macos-latest
        compiler:
          - zig
          - gcc
        # target:
        #   - x86_64-linux
          # - x86_64-macos
          # - x86_64-windows-gnu

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
          cache: 'pip' # caching pip dependencies
      - uses: goto-bus-stop/setup-zig@v2
        with:
          # version: master
          version: 0.12.0-dev.3161+377ecc6af
          cache: false
      - 
        name: Build with Nuikta and Zig
        shell: bash
        run: |
          chmod ugo+x *.sh
          # export TARGET=${{ matrix.target }}

          if [[ -n "$WINDIR" ]]; then
            SCRIPT_EXT="sh"
          else
            SCRIPT_EXT="bat"
          fi
          if [[ "${{ matrix.compiler }}" == 'zig' ]]; then
            export CC="$(pwd)/zig-clang-cc.$SCRIPT_EXT"
            export CXX="$(pwd)/zig-clang++.$SCRIPT_EXT"
          fi

          pip install -r requirements.txt
          python -m nuitka \
            --show-scons \
            --clang \
            --static-libpython=no \
            --assume-yes-for-downloads \
            --standalone \
            hello.py
          ./hello.dist/hello.*
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: standalone-${{matrix.os}}-python-${{matrix.python_version}}-${{matrix.compiler}}
          path: |
            nuitka-crash-report.xml
            hello.dist/**/*
            hello.bin
          
