name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.9, 3.10, 3.11]
        os: [ubuntu-latest]
        # target:
        #   - x86_64-linux
          # - x86_64-macos
          # - x86_64-windows-gnu

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
          cache: 'pip' # caching pip dependencies
      - uses: goto-bus-stop/setup-zig@v2
        with:
          # version: master
          version: 0.12.0-dev.3161+377ecc6af
          cache: false
      - 
        name: Build with Nuikta and Zig
        run: |
          chmod ugo+x *.sh
          # export TARGET=${{ matrix.target }}
          export CXX="$(pwd)/zig-clang++.sh"
          export CC="$(pwd)/zig-clang-cc.sh"
          pip install -r requirements.txt
          python -m nuitka \
            --show-scons \
            --clang \
            --standalone \
            hello.py
          ./hello.bin
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: standalone-${{matrix.os}}-python-${{matrix.python_version}}
          path: |
            nuitka-crash-report.xml
            hello.dist/**/*
            hello.bin
          
